repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix, src/, tests/]
        files: ^(src|tests)/
        exclude: ^(steering|demos|docs|site)/|\.ipynb$
      - id: ruff-format
        args: [src/, tests/]
        files: ^(src|tests)/
        exclude: ^(steering|demos|docs|site)/|\.ipynb$
