---

opt:
  base: base_opt
  odir: _
  resume: false

---

opt.0:
  base: base_opt.0
  likelihood: =lh.0

lh.0:
  sky: =sky.0
  data: =data.0
  noise:
    prefix: nm.0
    parameters: {}
    scaling: false
    varcov: false
  mode: _

data.0:
  fname: _
  mode: _

sky.0:
  prefix: sky.0
  background: =sky_bg.0

sky_bg.0:
  prefix: bg.0
  grid:
    base: grid_bg
  freq: [1.]
  params:
    base: params_sf
  offset: 12
