---

# specify the main pipeline settings (output directory, key, number of iterations, and the trained U-Net)
odir: runs/fast_vi_1f_1024_1z_c
key: 42

n_it: 5

# additional plots (saved if true)
callback: true
extra: true
trans: true
rerun: true

--- 

# specify the data to be reconstructed and the background grid (space and field of view)
data:
  fname: /scratch/users/rfuchs/data/eso_986-1137mhz.npz
  fun: fast_radio

grid_bg:
  space: [1024, 1024]
  fov: [2deg, 2deg]

noise:
  parameters:
    mode: 1.0
    mean: 1.1
  scaling: true

split: 512

---

# overwrite the default inference settings
base_opt.0:
  n_total_iterations: 10
  n_major_iterations: 10
  n_minor_iterations: 2
  n_samples: 2
  draw_linear_kwargs:
    cg_name: SL
    cg_kwargs:
      absdelta: 1.0e-11
      miniter: 2*[100] + 2*[200] + 2*[350] + 2*[500] + [100]
      maxiter: 2*[100] + 2*[200] + 2*[350] + 2*[500] + [1000]
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: SN
      xtol: 0.0001
      cg_kwargs:
        name: null
      miniter: 0
      maxiter: 10
  kl_kwargs:
    minimize_kwargs:
      name: M
      absdelta: 1.0e-10
      cg_kwargs:
        name: null
        miniter: 2*[5] + 2*[10] + [20]
      miniter: 2*[5] + 2*[10] + 2*[20] + 2*[35] + [10]
      maxiter: 2*[5] + 2*[10] + 2*[20] + 2*[35] + [50]
      energy_reduction_factor: 0.001
  sample_mode: 4*[linear_resample] + [nonlinear_resample]

base_opt.n:
  n_total_iterations: 10
  n_major_iterations: 10
  n_minor_iterations: 2
  n_samples: 2
  draw_linear_kwargs:
    cg_name: SL
    cg_kwargs:
      absdelta: 1.0e-11
      miniter: 1000
      maxiter: 2000
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: SN
      xtol: 0.0001
      cg_kwargs:
        name: null
      miniter: 10
      maxiter: 20
  kl_kwargs:
    minimize_kwargs:
      name: M
      absdelta: 1.0e-10
      cg_kwargs:
        name: null
        miniter: 20
      miniter: 100
      maxiter: 200
      energy_reduction_factor: 0.001
  sample_mode: nonlinear_resample

base_trans:
  n_total_iterations: 20
  n_samples: 1
  draw_linear_kwargs:
    cg_name: SL
    cg_kwargs:
      absdelta: 1.0e-11
      miniter: 4*[100] + 4*[200] + 4*[350] + 4*[500] + [100]
      maxiter: 4*[100] + 4*[200] + 4*[350] + 4*[500] + [1000]
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: SN
      xtol: 0.0001
      cg_kwargs:
        name: null
      miniter: 0
      maxiter: 10
  kl_kwargs:
    minimize_kwargs:
      name: M
      absdelta: 1.0e-10
      cg_kwargs:
        name: null
        miniter: 4*[5] + 4*[10] + [20]
      miniter: 4*[5] + 4*[10] + 4*[20] + 4*[35] + [10]
      maxiter: 4*[5] + 4*[10] + 4*[20] + 4*[35] + [50]
      energy_reduction_factor: 0.001
  sample_mode: 8*[linear_resample] + [nonlinear_resample]

---

# overwrite the default segmentation parameters
base_seg:
  seg_model:
    name: unet1024_dice30
    odir: train/runs/files
  transform:
    log: true
    normalize: true
    standardize: false
    rotate: false
    flip: false
  n_orders: 5
  coordinates: false

# overwrite the default clustering parameters
base_clu:
  alg: dbscan
  eps: 0.2
  min_samples: 2

# overwrite the default modelling settings
base_model:
  zoom: 4
  masks:
    margin_fac: 0.2
    margin_min: 5
    max_objects: 5
  points: true
  objects:
    gaussian:
      mean_fac: 0.1
      std_fac: 0.01
  tiles:
    tile_size: 32
    gaussian:
      mean_fac: 0.1
      std_fac: 0.01

# overwrite the default plotting settings
base_plot:
  vmin: null
  vmax: null
  cbar: true
  ticks: 0
  plot_grid: false
  plot_label: false
