name: uno_1

odir: files

device: cpu

dataset:
  train:
    name: train_128
    odir: ../data/files
    dtype: float32
    size: 10
  valid:
    _128:
      name: valid_128
      odir: ../data/files
      dtype: float32
      size: 10
  transform:
    log: true
    normalize: true
    standardize: false
    rotate: true
    flip: true
  coordinates: true

dataloader:
  train:
    batch_size: 4
    shuffle: true
    num_workers: 0
    pin_memory: true
  valid:
    _128:
      batch_size: 4
      num_workers: 0
      shuffle: false
      pin_memory: true

model:
  in_channels: 3
  out_channels: 2
  hidden_channels: 64
  projection_channels: 64
  positional_embedding: null
  uno_out_channels: [32]
  uno_n_modes: [[16, 16]]
  uno_scalings: [[1.0, 1.0]]
  horizontal_skips_map: null
  channel_mlp_skip: linear
  n_layers: 1
  domain_padding: 0.2

optimizer:
  lr: 0.008
  weight_decay: 0.0001

scheduler:
  T_max: 30

trainer:
  n_epochs: 1
  wandb_log: false
  eval_interval: 1
  use_distributed: false
  verbose: true

plot:
  odir: plots
  n_copies: 5
  plot_space: true
  plot_label: true
  cmap: inferno

