---

name: uno_1
odir: training

---

dataset:
  name: train128_1k
  odir: /scratch/users/rfuchs/packages/tile-nifty/tests/data/files
  dtype: float32
  size: 1000
  split: 0.8
  coos: true
  transform:
    log: true
    normalize: true
    standardize: false
    rotate: true
    flip: true

dataloader:
  train:
    batch_size: 32
    shuffle: true
    num_workers: 0
    pin_memory: true
  test:
    128:
      batch_size: 32
      num_workers: 0
      shuffle: false
      pin_memory: true

model:
  name: UNO
  in_channels: 3
  out_channels: 2
  hidden_channels: 64
  projection_channels: 64
  positional_embedding: null
  uno_out_channels: [32] #,64,64,64,32],
  uno_n_modes: [[16,16]] #,[8,8],[8,8],[8,8],[16,16]],
  uno_scalings: [[1.0,1.0]] #,[0.5,0.5],[1,1],[2,2],[1,1]],
  horizontal_skips_map: null
  channel_mlp_skip: linear
  n_layers: 1
  domain_padding: 0.2

optimizer:
  name: AdamW
  lr: 8.e-3
  weight_decay: 1.e-4

scheduler:
  name: CosineAnnealingLR

loss:
  train:
    name: BCEwithLogitsLoss
  test:
    name: BCEwithLogitsLoss

trainer:
  n_epochs: 100
  device: device
  wandb_log: False
  eval_interval: 3
  use_distributed: False
  verbose: True

---

plot:
  n_copies: 10
  space: True
  label: True
  cmap: inferno
  norm: [log, linear, linear]
