---

base_opt.0:
  n_total_iterations: 10
  n_major_iterations: 10
  n_minor_iterations: 2
  n_samples: 2
  draw_linear_kwargs:
    cg_name: SL
    cg_kwargs:
      absdelta: 1.e-11
      miniter: 2*[100] + 2*[200] + 2*[350] + 2*[500] + [100]
      maxiter: 2*[100] + 2*[200] + 2*[350] + 2*[500] + [1000]
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: SN
      xtol: 1.e-4
      cg_kwargs:
        name: null
      miniter: 0
      maxiter: 10
  kl_kwargs:
    minimize_kwargs:
      name: M
      absdelta: 1.e-10
      cg_kwargs:
        name: null
        miniter: 2*[5] + 2*[10] + [20]
      miniter: 2*[5] + 2*[10] + 2*[20] + 2*[35] + [10]
      maxiter: 2*[5] + 2*[10] + 2*[20] + 2*[35] + [50]
      energy_reduction_factor: 1.e-3
  sample_mode: 4*[linear_resample] + [nonlinear_resample]

base_opt.n:
  n_total_iterations: 10
  n_major_iterations: 10
  n_minor_iterations: 2
  n_samples: 2
  draw_linear_kwargs:
    cg_name: SL
    cg_kwargs:
      absdelta: 1.e-11
      miniter: 1000
      maxiter: 2000
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: SN
      xtol: 1.e-4
      cg_kwargs:
        name: null
      miniter: 10
      maxiter: 20
  kl_kwargs:
    minimize_kwargs:
      name: M
      absdelta: 1.e-10
      cg_kwargs:
        name: null
        miniter: 20
      miniter: 100
      maxiter: 200
      energy_reduction_factor: 1.e-3
  sample_mode: nonlinear_resample

base_trans:
  n_total_iterations: 20
  n_samples: 1
  draw_linear_kwargs:
    cg_name: SL
    cg_kwargs:
      absdelta: 1.e-11
      miniter: 4*[100] + 4*[200] + 4*[350] + 4*[500] + [100]
      maxiter: 4*[100] + 4*[200] + 4*[350] + 4*[500] + [1000]
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: SN
      xtol: 1.e-4
      cg_kwargs:
        name: null
      miniter: 0
      maxiter: 10
  kl_kwargs:
    minimize_kwargs:
      name: M
      absdelta: 1.e-10
      cg_kwargs:
        name: null
        miniter: 4*[5] + 4*[10] + [20]
      miniter: 4*[5] + 4*[10] + 4*[20] + 4*[35] + [10]
      maxiter: 4*[5] + 4*[10] + 4*[20] + 4*[35] + [50]
      energy_reduction_factor: 1.e-3
  sample_mode: 8*[linear_resample] + [nonlinear_resample]

---

params_sf:
  i0:
    offset_std: [1, 1]
    fluctuations: [5, 1]
    loglogavgslope: [-2, 0.5]
    flexibility: [1.2, 0.4]
    asperity: [0.2, 0.2]

params_mf:
  zero_mode: [1, 1]
  spatial_amplitude:
    fluctuations: [5, 1]
    loglogavgslope: [-2, 0.5]
    flexibility: [1.2, 0.4]
    asperity: [0.2, 0.2]
  spectral_index:
    mean: [-1, 0.5]
    fluctuations: [3, 1]
  spectral_amplitude:
    loglogavgslope: [-2, 0.5]
    flexibility: [1.2, 0.4]
    asperity: [0.2, 0.2]
  deviations:
    process: wiener
    sigma: [0.2, 0.08]

params_ps:
  i0:
    mean: 0
    std: 3
  alpha:
    mean: -1
    std: 0.5
  deviations:
    process: wiener
    sigma: [0.2, 0.08]
