---

odir: /scratch/users/rfuchs/packages/aim-resolve/steering/runs/fast_vi_1f_1024_1z_b
base: base.yml
file: 4_pre_2z_1.yml
run: 1

---

mode: freq
freq: [992153320.3125, 1053594726.5625, 1114618164.0625, 1329454101.5625, 1398998058.6408134,
    1468637695.3125]
ref_freq_index: 1

---

opt.6:
  base: base_opt.6
  likelihood: =lh.6

lh.6:
  data: =data.6
  mode: fast
  # split:
  #   size: 256
  #   factor: 2

data.6:
  fname: /scratch/users/rfuchs/data/eso_961-1503mhz.npz
  mode: radio

base_opt.6:
  n_major_iterations: 10
  n_minor_iterations: 1
  n_samples: 2
  draw_linear_kwargs:
    cg_name: SL
    cg_kwargs:
      absdelta: 1.e-11
      miniter: 2*[100] + 2*[200] + 2*[350] + 2*[500] + [100]
      maxiter: 2*[100] + 2*[200] + 2*[350] + 2*[500] + [1000]
  nonlinearly_update_kwargs:
    minimize_kwargs:
      name: SN
      xtol: 1.e-4
      cg_kwargs:
        name: null
      miniter: 0
      maxiter: 10
  kl_kwargs:
    minimize_kwargs:
      name: M
      absdelta: 1.e-10
      cg_kwargs:
        name: null
        miniter: 2*[5] + 2*[10] + [20]
      miniter: 2*[5] + 2*[10] + 2*[20] + 2*[35] + [10]
      maxiter: 2*[5] + 2*[10] + 2*[20] + 2*[35] + [50]
      energy_reduction_factor: 1.e-3
  sample_mode: 4*[linear_resample] + [nonlinear_resample]
