---

odir: /scratch/users/rfuchs/packages/aim-resolve/steering/runs/fast_vi_1f_1024_1z_b
base: base.yml
file: 3_pre_2z.yml

---

mode: freq
freq: [992153320.3125, 1053594726.5625, 1114618164.0625, 1329454101.5625, 1398998058.6408134,
    1468637695.3125]
ref_freq_index: 1

---

opt.5:
  base: base_opt.0
  likelihood: =lh.5

lh.5:
  data: =data.5
  mode: fast
  # split:
  #   size: 256
  #   factor: 2

data.5:
  fname: /scratch/users/rfuchs/data/eso_961-1503mhz.npz
  mode: radio
  nrow: 1000
