---

odir: /scratch/users/rfuchs/packages/aim-resolve/steering/runs/fast_vi_1f_1024_1z_b
base: base.yml
file: 4_pre.yml
run: 1

---

mode: zoom
zoom: 3

---

# lh.4:
#   split:
#     size: 512
#     factor: 2
